### ISSUE TITLE
Fix file descriptions

### ISSUE THREAD

**Issue by rflprr** [datadotworld/ckanext-datadotworld#4] opened 2017-05-19 18:21 UTC
Currently, if I enter a description for a resource, the file created on data.world is created without a description.

Instead, the file on data.world should show the same description content.

See: https://docs.data.world/documentation/api/addFiles.html

**Comment by iaroslav13** [comment] 2017-05-24 02:25
It is fixed in #7 

I noticed that when the file cannot be downloaded on data.world, it doesn't show any description on front end. When dataset (and files) are requested, description is returned. For successfully downloaded files, description is shown.

**Comment by iaroslav13** [comment] 2017-05-25 22:44
These changes caused issues you described in #2 

If you go to failed dataset replication (/data.world/failed), you will see the following error for some datasets: `nvalid DatasetPutRequest . Violations = [ConstraintViolationImpl{interpolatedMessage='File description size must be between 1 and 120', propertyPath=files[1].description`

This is caused by empty "description" property. We will fix it on our end. But I guess, it would be good if the API accepts empty description.

**Comment by iaroslav13** [comment] 2017-05-26 00:28
@rflprr it looks like 120 signs for a description is not enough in a lot of the cases. In this case I guess we will clip it and add an ellipsis, if it exceeds 120 chars. Can you see any issues with this?

Of course, Ideally, it would be good to have higher limit for file's description.

**Comment by rflprr** [comment] 2017-05-30 14:30
@iaroslav13 I want to make sure that you are not confusing CKAN description with data.world description.

To be clear, your title should be the description on data.world. And your description should be the summary on data.world. Your title is short, our description is short. Your description is long and our summary is long too (25k characters with support for markdown).

**Comment by rflprr** [comment] 2017-05-30 14:35
@iaroslav13 Thanks. Yeah, the limit is a bit restrictive, but for now, let's just convert markdown into plain text and truncate.

**Comment by rflprr** [comment] 2017-05-30 14:38
@iaroslav13 On empty descriptions, you can send `null` and that _should_ work.

**Closed** 2017-06-23 19:49 UTC
