### ISSUE TITLE
Fix mapping of title, description and summary

### ISSUE THREAD

**Issue by rflprr** [datadotworld/ckanext-datadotworld#2] opened 2017-05-19 17:53 UTC
When updating a dataset in CKAN:
1) Changing the title does not change the dataset in data.world
2) Changing the description changes both description and summary in data.world

Instead, the mapping from CKAN to data.world should be:
1) ckan:ID -> dw:title
2) ckan:title -> dw:description
3) ckan:notes -> dw:summary

**Comment by iaroslav13** [comment] 2017-05-24 02:26
Fixed in #7

**Comment by rflprr** [comment] 2017-05-25 13:50
@iaroslav13 This seems to have introduced a pretty serious bug. I'm unable to create or update any datasets at the moment.

**Comment by iaroslav13** [comment] 2017-05-25 22:46
The issue is related to #4 . We will fix it on our end.

For now, you can add descriptions to files and the datasets will be replicated. You can use Failed Dataset Replications page to get some information about the errors.

**Comment by iaroslav13** [comment] 2017-05-26 05:29
Also there is an issue with the API, it looks like when dataset is updated (and new title is set), it's not updated on data.world. At least it is not reflected on front-end

**Comment by rflprr** [comment] 2017-05-30 14:37
Seems fine, upon testing. I'll test some more.

**Comment by rflprr** [comment] 2017-06-23 19:49
@iaroslav13 This is good for now. The only problem I see is with the `ckan:ID > dw:title` mapping. `dw:title` is typically a human readable dataset name (up to 60 characters). I don't think a similar concept exists on the CKAN side so, although not ideal, `ckan:ID` might be the best option we have there. Thoughts?

**Closed** 2017-06-23 19:49 UTC
